"""
ISRO MOSDAC adapter — downloads and queries OCM-3 analyzed chlorophyll
(E06OCM_L4_AC) from the EOS-06 (Oceansat-3) satellite via the MOSDAC
Download API.

API flow (reverse-engineered from MOSDAC's official mdapi.py tool):
  1. POST /download_api/gettoken  → {access_token, refresh_token}
  2. GET  /apios/datasets.json?datasetId=...&startTime=...&endTime=...
     → paginated search results with record IDs
  3. GET  /download_api/download?id=<record_id>  (Bearer token)
     → NetCDF file stream

This adapter does two things:
  - `fetch_latest_chlorophyll()`: downloads the most recent L4 chlorophyll
    file to data/raw/mosdac/, caches it, and returns the local path.
  - `get_chlorophyll_at(lat, lon)`: opens the cached file and extracts the
    chlorophyll value at the nearest grid point.

Both short-circuit cleanly when credentials are absent.
"""
import asyncio
import logging
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path

import httpx
import numpy as np

from app.core.config import settings
from app.tools._executor import network_executor

logger = logging.getLogger(__name__)

# MOSDAC API endpoints (from official mdapi.py)
TOKEN_URL = "https://mosdac.gov.in/download_api/gettoken"
SEARCH_URL = "https://mosdac.gov.in/apios/datasets.json"
DOWNLOAD_URL = "https://mosdac.gov.in/download_api/download"

# EOS-06 OCM-3 L4 Analyzed Chlorophyll — the most useful product for JalJeev.
# Generated by assimilating OCM-3 observations into a coupled physical-
# biogeochemical model (MOM5 + TOPAZ). Available from 2023-06-20 onward.
CHLOROPHYLL_DATASET_ID = "E06OCM_L4_AC"

REPO_ROOT = Path(__file__).resolve().parents[3]
MOSDAC_CACHE_DIR = REPO_ROOT / "data" / "raw" / "mosdac"
MOSDAC_CACHE_DIR.mkdir(parents=True, exist_ok=True)

# Don't re-download if the cached file is younger than this.
CACHE_MAX_AGE_HOURS = 24

# Timeout for individual HTTP requests to MOSDAC (seconds).
REQUEST_TIMEOUT = 30


def _is_configured() -> bool:
    return bool(settings.MOSDAC_USERNAME and settings.MOSDAC_PASSWORD)


def _unavailable(reason: str) -> dict:
    return {
        "source": "ISRO MOSDAC (EOS-06 OCM-3)",
        "status": "unavailable",
        "reason": reason,
    }


async def _get_token() -> dict | None:
    """Authenticate with MOSDAC and return {access_token, refresh_token}."""
    try:
        async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT) as client:
            resp = await client.post(
                TOKEN_URL,
                json={
                    "username": settings.MOSDAC_USERNAME,
                    "password": settings.MOSDAC_PASSWORD,
                },
            )
            if resp.status_code == 401:
                logger.error("MOSDAC auth failed: invalid credentials")
                return None
            if resp.status_code == 400:
                err = resp.json().get("error", "unknown validation error")
                logger.error(f"MOSDAC auth validation error: {err}")
                return None
            resp.raise_for_status()
            return resp.json()
    except Exception as exc:
        logger.error(f"MOSDAC auth error: {type(exc).__name__}: {exc}")
        return None


async def _search_latest(dataset_id: str, days_back: int = 7) -> dict | None:
    """Search for the most recent file of a given dataset."""
    end = datetime.now(timezone.utc)
    start = end - timedelta(days=days_back)
    params = {
        "datasetId": dataset_id,
        "startTime": start.strftime("%Y-%m-%d"),
        "endTime": end.strftime("%Y-%m-%d"),
    }
    try:
        async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT) as client:
            resp = await client.get(SEARCH_URL, params=params)
            resp.raise_for_status()
            data = resp.json()
            entries = data.get("entries", [])
            if not entries:
                # Widen the window and try again
                if days_back < 30:
                    return await _search_latest(dataset_id, days_back=30)
                return None
            # Return the most recent entry (first in the list, usually sorted desc)
            return entries[0]
    except Exception as exc:
        logger.error(f"MOSDAC search error: {type(exc).__name__}: {exc}")
        return None


async def _download_file(record_id: str, filename: str, access_token: str) -> Path | None:
    """Download a single file from MOSDAC to the local cache."""
    file_path = MOSDAC_CACHE_DIR / filename
    if file_path.exists():
        age_hours = (datetime.now().timestamp() - file_path.stat().st_mtime) / 3600
        if age_hours < CACHE_MAX_AGE_HOURS:
            logger.info(f"MOSDAC cache hit: {filename} ({age_hours:.1f}h old)")
            return file_path

    headers = {"Authorization": f"Bearer {access_token}"}
    params = {"id": record_id}
    try:
        async with httpx.AsyncClient(timeout=120) as client:
            resp = await client.get(DOWNLOAD_URL, headers=headers, params=params)
            if resp.status_code == 401:
                logger.error("MOSDAC download: token expired or invalid")
                return None
            if resp.status_code == 404:
                logger.warning(f"MOSDAC download: file {record_id} not found on server")
                return None
            resp.raise_for_status()

            content_disp = resp.headers.get("Content-Disposition", "")
            if "filename=" not in content_disp:
                logger.warning(f"MOSDAC: file {record_id} not available on server")
                return None

            tmp_path = file_path.with_suffix(".part")
            tmp_path.write_bytes(resp.content)
            tmp_path.rename(file_path)
            logger.info(f"MOSDAC downloaded: {filename} ({len(resp.content) / 1024:.0f} KB)")
            return file_path
    except Exception as exc:
        logger.error(f"MOSDAC download error: {type(exc).__name__}: {exc}")
        return None


async def fetch_latest_chlorophyll() -> Path | None:
    """
    Download the most recent L4 analyzed chlorophyll file from MOSDAC.
    Returns the local file path, or None on failure.
    """
    if not _is_configured():
        return None

    tokens = await _get_token()
    if not tokens:
        return None

    entry = await _search_latest(CHLOROPHYLL_DATASET_ID)
    if not entry:
        logger.warning("MOSDAC: no recent chlorophyll files found")
        return None

    record_id = entry.get("id")
    filename = entry.get("identifier", f"mosdac_chl_{record_id}.nc")

    return await _download_file(record_id, filename, tokens["access_token"])


def _extract_chlorophyll_sync(file_path: Path, lat: float, lon: float) -> float | None:
    """
    Open a NetCDF file and extract the chlorophyll value at the nearest
    grid point to (lat, lon). Runs in a thread (blocking I/O).
    """
    try:
        import xarray as xr
    except ImportError:
        logger.error("xarray not installed — cannot read MOSDAC NetCDF files")
        return None

    try:
        ds = xr.open_dataset(file_path)
        # MOSDAC L4 analyzed chlorophyll uses 'chla' as the variable name,
        # with 'lat'/'lon'/'lev'/'time' coordinates. Try common names as
        # fallback in case the schema changes.
        chl_var = None
        for name in ("chla", "chl", "chlorophyll", "CHL", "Chlorophyll", "analysed_chl"):
            if name in ds.data_vars:
                chl_var = name
                break
        if chl_var is None:
            # Fall back to the first non-coordinate variable
            data_vars = [v for v in ds.data_vars if v not in ("lat", "lon", "time", "lev")]
            if data_vars:
                chl_var = data_vars[0]
                logger.info(f"MOSDAC: using variable '{chl_var}' as chlorophyll")
            else:
                logger.warning(f"MOSDAC: no data variables found in {file_path.name}")
                ds.close()
                return None

        # Find the nearest grid point
        da = ds[chl_var]
        # Handle different coordinate naming conventions
        lat_coord = "latitude" if "latitude" in ds.coords else "lat"
        lon_coord = "longitude" if "longitude" in ds.coords else "lon"

        val = da.sel(**{lat_coord: lat, lon_coord: lon}, method="nearest")
        # If there's a time dimension, take the latest
        if "time" in val.dims:
            val = val.isel(time=-1)
        # If there's a depth dimension, take the surface
        for dim in ("depth", "z", "level"):
            if dim in val.dims:
                val = val.isel(**{dim: 0})

        result = float(val.values)
        ds.close()

        if np.isnan(result):
            return None
        return result
    except Exception as exc:
        logger.error(f"MOSDAC chlorophyll extraction error: {type(exc).__name__}: {exc}")
        return None


async def get_chlorophyll_at(lat: float, lon: float) -> dict:
    """
    Get ISRO OCM-3 analyzed chlorophyll at a given location.
    Downloads the latest file if needed, then extracts the value.
    """
    if not _is_configured():
        return _unavailable("MOSDAC credentials not configured")

    file_path = await fetch_latest_chlorophyll()
    if file_path is None:
        return {
            "source": "ISRO MOSDAC (EOS-06 OCM-3)",
            "status": "failed",
            "reason": "Could not download latest chlorophyll data from MOSDAC",
        }

    loop = asyncio.get_running_loop()
    value = await loop.run_in_executor(
        network_executor, _extract_chlorophyll_sync, file_path, lat, lon
    )

    if value is None:
        return {
            "source": "ISRO MOSDAC (EOS-06 OCM-3)",
            "status": "failed",
            "reason": f"No chlorophyll data at ({lat:.2f}, {lon:.2f}) in the latest MOSDAC file",
        }

    return {
        "source": "ISRO MOSDAC (EOS-06 OCM-3)",
        "status": "success",
        "chlorophyll_mg_m3": round(value, 3),
        "product": CHLOROPHYLL_DATASET_ID,
        "file": file_path.name,
        "fetched_at": datetime.now(timezone.utc).isoformat(),
    }


# Legacy function signature — used by the existing adapter contract.
# Kept for backward compatibility; now returns chlorophyll instead of PFZ.
async def get_pfz_advisory(lat: float, lon: float, date: str | None = None) -> dict:
    """
    Original stub function. PFZ advisories are NOT available on MOSDAC
    (they live on the INCOIS portal). This now returns chlorophyll data
    instead, which is the primary useful product from MOSDAC for JalJeev.
    """
    if not _is_configured():
        return _unavailable("MOSDAC credentials not configured (registration pending)")

    chl = await get_chlorophyll_at(lat, lon)
    chl["note"] = (
        "PFZ advisories are published by INCOIS (incois.gov.in), not MOSDAC. "
        "This adapter provides ISRO OCM-3 analyzed chlorophyll from EOS-06 instead."
    )
    return chl
