import type { PassagePlan } from "./api";

/**
 * Hardcoded verified sample passage navigating from Kochi to Goa Port (Mormugao).
 * Follows the Arabian Sea coastal corridor (~15-25 nm offshore).
 * Used as an instant travel example and benchmark demonstration.
 */
export const KOCHI_TO_GOA_SAMPLE_PASSAGE: PassagePlan = {
  origin_name: "Kochi (Cochin)",
  origin_lat: 9.965,
  origin_lon: 76.22,
  destination_name: "Goa (Mormugao)",
  destination_lat: 15.41,
  destination_lon: 73.79,
  vessel_class: "fishing_small",
  vessel_name: "Small Mechanized Trawler (8m)",
  found_route: true,
  reason: null,
  direct_distance_nm: 356.5,
  routed_distance_nm: 358.9,
  sailed_distance_nm: 358.9,
  total_eta_hours: 47.9,
  max_leg_risk_score: 15,
  max_leg_risk_level: "LOW",
  h3_resolution: 4,
  cells_evaluated: 94,
  cells_viable: 88,
  forecast_note:
    "Sample voyage: Verified coastal corridor navigation from Kochi to Goa Port (Mormugao). All legs scored under favourable sea states with deep-water clearances and diversion ports en route.",
  destination_maps_url: "https://www.google.com/maps/search/?api=1&query=15.41,73.79",
  waypoints: [
    {
      lat: 9.965,
      lon: 76.22,
      risk_score: 10,
      name: "Kochi Port Approach Channel",
    },
    {
      lat: 10.55,
      lon: 75.9,
      risk_score: 12,
      name: "Off Chavakkad / Thrissur",
    },
    {
      lat: 11.25,
      lon: 75.65,
      risk_score: 13,
      name: "Off Kozhikode (Calicut)",
    },
    {
      lat: 11.85,
      lon: 75.25,
      risk_score: 11,
      name: "Off Kannur Coast",
    },
    {
      lat: 12.5,
      lon: 74.88,
      risk_score: 12,
      name: "Off Kasaragod / Bekal",
    },
    {
      lat: 12.92,
      lon: 74.7,
      risk_score: 15,
      name: "Off New Mangalore Port",
    },
    {
      lat: 13.35,
      lon: 74.58,
      risk_score: 12,
      name: "Off Malpe / Udupi",
    },
    {
      lat: 13.98,
      lon: 74.45,
      risk_score: 13,
      name: "Off Bhatkal / Kundapura",
    },
    {
      lat: 14.8,
      lon: 74.05,
      risk_score: 12,
      name: "Off Karwar Bay",
    },
    {
      lat: 15.41,
      lon: 73.79,
      risk_score: 10,
      name: "Goa Mormugao Port Fairway",
    },
  ],
  legs: [
    {
      from_lat: 9.965,
      from_lon: 76.22,
      to_lat: 10.55,
      to_lon: 75.9,
      bearing_deg: 334.8,
      distance_nm: 39.5,
      sailed_distance_nm: 39.5,
      eta_hours_from_departure: 5.3,
      risk_score: 12,
      risk_level: "LOW",
      forecast_hour_offset: 5,
      beyond_forecast_horizon: false,
      must_tack: false,
      explanation: [
        "Off Chavakkad / Thrissur: Open coastal passage in Arabian Sea.",
        "Bathymetric depth 34m — well clear of vessel draft (1.2m).",
        "Significant wave height 1.1m, wind 11 kn from NW.",
        "Outside all marine protected areas and coastal exclusion zones.",
      ],
    },
    {
      from_lat: 10.55,
      from_lon: 75.9,
      to_lat: 11.25,
      to_lon: 75.65,
      bearing_deg: 340.7,
      distance_nm: 44.5,
      sailed_distance_nm: 44.5,
      eta_hours_from_departure: 11.3,
      risk_score: 13,
      risk_level: "LOW",
      forecast_hour_offset: 11,
      beyond_forecast_horizon: false,
      must_tack: false,
      explanation: [
        "Off Kozhikode (Calicut): Open coastal passage in Arabian Sea.",
        "Bathymetric depth 46m — well clear of vessel draft (1.2m).",
        "Significant wave height 1.2m, wind 12 kn from WNW.",
        "Outside all marine protected areas and coastal exclusion zones.",
      ],
    },
    {
      from_lat: 11.25,
      from_lon: 75.65,
      to_lat: 11.85,
      to_lon: 75.25,
      bearing_deg: 326.9,
      distance_nm: 43.0,
      sailed_distance_nm: 43.0,
      eta_hours_from_departure: 17.0,
      risk_score: 11,
      risk_level: "LOW",
      forecast_hour_offset: 16,
      beyond_forecast_horizon: false,
      must_tack: false,
      explanation: [
        "Off Kannur Coast: Open coastal passage in Arabian Sea.",
        "Bathymetric depth 48m — well clear of vessel draft (1.2m).",
        "Significant wave height 1.0m, wind 10 kn from NW.",
        "Outside all marine protected areas and coastal exclusion zones.",
      ],
    },
    {
      from_lat: 11.85,
      from_lon: 75.25,
      to_lat: 12.5,
      to_lon: 74.88,
      bearing_deg: 330.9,
      distance_nm: 44.7,
      sailed_distance_nm: 44.7,
      eta_hours_from_departure: 22.9,
      risk_score: 12,
      risk_level: "LOW",
      forecast_hour_offset: 22,
      beyond_forecast_horizon: false,
      must_tack: false,
      explanation: [
        "Off Kasaragod / Bekal: Open coastal passage in Arabian Sea.",
        "Bathymetric depth 52m — well clear of vessel draft (1.2m).",
        "Significant wave height 1.1m, wind 11 kn from WNW.",
        "Outside all marine protected areas and coastal exclusion zones.",
      ],
    },
    {
      from_lat: 12.5,
      from_lon: 74.88,
      to_lat: 12.92,
      to_lon: 74.7,
      bearing_deg: 337.3,
      distance_nm: 27.3,
      sailed_distance_nm: 27.3,
      eta_hours_from_departure: 26.6,
      risk_score: 15,
      risk_level: "LOW",
      forecast_hour_offset: 26,
      beyond_forecast_horizon: false,
      must_tack: false,
      explanation: [
        "Off New Mangalore Port: Open coastal passage in Arabian Sea.",
        "Bathymetric depth 42m — well clear of vessel draft (1.2m).",
        "Significant wave height 1.2m, wind 13 kn from NW.",
        "Outside all marine protected areas and coastal exclusion zones.",
      ],
    },
    {
      from_lat: 12.92,
      from_lon: 74.7,
      to_lat: 13.35,
      to_lon: 74.58,
      bearing_deg: 344.8,
      distance_nm: 26.8,
      sailed_distance_nm: 26.8,
      eta_hours_from_departure: 30.2,
      risk_score: 12,
      risk_level: "LOW",
      forecast_hour_offset: 30,
      beyond_forecast_horizon: false,
      must_tack: false,
      explanation: [
        "Off Malpe / Udupi: Open coastal passage in Arabian Sea.",
        "Bathymetric depth 45m — well clear of vessel draft (1.2m).",
        "Significant wave height 1.0m, wind 11 kn from NW.",
        "Outside all marine protected areas and coastal exclusion zones.",
      ],
    },
    {
      from_lat: 13.35,
      from_lon: 74.58,
      to_lat: 13.98,
      to_lon: 74.45,
      bearing_deg: 348.7,
      distance_nm: 38.6,
      sailed_distance_nm: 38.6,
      eta_hours_from_departure: 35.3,
      risk_score: 13,
      risk_level: "LOW",
      forecast_hour_offset: 35,
      beyond_forecast_horizon: false,
      must_tack: false,
      explanation: [
        "Off Bhatkal / Kundapura: Open coastal passage in Arabian Sea.",
        "Bathymetric depth 50m — well clear of vessel draft (1.2m).",
        "Significant wave height 1.1m, wind 12 kn from WNW.",
        "Outside all marine protected areas and coastal exclusion zones.",
      ],
    },
    {
      from_lat: 13.98,
      from_lon: 74.45,
      to_lat: 14.8,
      to_lon: 74.05,
      bearing_deg: 334.8,
      distance_nm: 54.5,
      sailed_distance_nm: 54.5,
      eta_hours_from_departure: 42.6,
      risk_score: 12,
      risk_level: "LOW",
      forecast_hour_offset: 42,
      beyond_forecast_horizon: false,
      must_tack: false,
      explanation: [
        "Off Karwar Bay: Open coastal passage in Arabian Sea.",
        "Bathymetric depth 44m — well clear of vessel draft (1.2m).",
        "Significant wave height 1.1m, wind 11 kn from NW.",
        "Outside all marine protected areas and coastal exclusion zones.",
      ],
    },
    {
      from_lat: 14.8,
      from_lon: 74.05,
      to_lat: 15.41,
      to_lon: 73.79,
      bearing_deg: 337.7,
      distance_nm: 39.6,
      sailed_distance_nm: 39.6,
      eta_hours_from_departure: 47.9,
      risk_score: 10,
      risk_level: "LOW",
      forecast_hour_offset: 47,
      beyond_forecast_horizon: false,
      must_tack: false,
      explanation: [
        "Goa Mormugao Port Fairway: Open coastal passage in Arabian Sea.",
        "Bathymetric depth 18m — well clear of vessel draft (1.2m).",
        "Significant wave height 0.9m, wind 9 kn from WNW.",
        "Outside all marine protected areas and coastal exclusion zones.",
      ],
    },
  ],
  diversion_ports: [
    {
      name: "Beypore (Kozhikode)",
      lat: 11.161,
      lon: 75.801,
      distance_km: 18.4,
      from_leg_index: 1,
    },
    {
      name: "New Mangalore Port",
      lat: 12.928,
      lon: 74.815,
      distance_km: 14.2,
      from_leg_index: 4,
    },
    {
      name: "Karwar Port",
      lat: 14.805,
      lon: 74.12,
      distance_km: 11.5,
      from_leg_index: 7,
    },
  ],
};
